import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Box } from "grommet";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}></header>
      <main className={styles.main}>
        <Box direction="row">
          <Box
            className={styles.day}
            margin="xsmall"
            background="#c52184"
          ></Box>
          <Box
            className={styles.day}
            margin="xsmall"
            background="#c52184"
          ></Box>
          <Box
            className={styles.day}
            margin="xsmall"
            background="#c52184"
          ></Box>
          <Box
            className={styles.day}
            margin="xsmall"
            background="#c52184"
          ></Box>
          <Box
            className={styles.day}
            margin="xsmall"
            background="#c52184"
          ></Box>
          <Box
            className={styles.day}
            margin="xsmall"
            background="#c52184"
          ></Box>
          <Box
            className={styles.day}
            margin="xsmall"
            background="#c52184"
          ></Box>
        </Box>
      </main>
      <footer></footer>
    </>
  );
}
