import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "./styles/Week.module.css";
import { Box } from "grommet";
import Day from "./components/Day";

export default function Home() {
  const dayNames = [
    "Sunday",
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
  ];

  const days = dayNames.map((name, i) => <Day key={i} name={name} />);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <header className={styles.header}></header> */}
      <main className={styles.week}>
        <Box direction="row">{days}</Box>
      </main>
      <footer></footer>
    </>
  );
}
